PR test linking

diff --git a/.github/workflows/PR.yml b/.github/workflows/PR.yml
--- a/.github/workflows/PR.yml
+++ b/.github/workflows/PR.yml
@@ -55,4 +55,23 @@ jobs:
       # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
       run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
       env:
-        SOCKET_LOG: trace
+        SOCKET_LOG: debug
+
+    - name: Install
+      run: cmake --install build --config Release
+
+    - name: Test Linking
+      working-directory: ${{github.workspace}}/tests/test_find_package
+      run: |
+        cmake -B build -DCMAKE_BUILD_TYPE=Release
+        cmake --build build --config Release
+        cd build
+        ./helloworld_server &
+        rsp=$(curl http://127.0.0.1:49999)
+        if [[ "$rsp" == "Hello, world\!" ]]; then
+          echo "Test passed"
+          exit 0
+        else
+          echo "Test failed"
+          exit 1
+        fi
