Add CI for macos and containers (#16)

diff --git a/.github/workflows/PR.yml b/.github/workflows/PR.yml
--- a/.github/workflows/PR.yml
+++ b/.github/workflows/PR.yml
@@ -11,10 +11,69 @@ env:
   BUILD_TYPE: Release
 
 jobs:
-  build:
-    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
-    # You can convert this to a matrix build if you need cross-platform coverage.
-    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
+  build-macos:
+    runs-on: macos-latest
+
+    strategy:
+      matrix:
+        shared: ["ON", "OFF"]
+
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          submodules: true
+
+      - name: Install LLVM and Clang
+        run: brew install llvm@16
+
+      - name: Install Rust toolchain
+        uses: actions-rs/toolchain@v1
+        with:
+          toolchain: nightly
+          default: true
+
+      - name: Configure CMake
+        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
+        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
+        run: |
+          eval "$(brew shellenv)"
+          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_SHARED_LIBS=${{ matrix.shared }}
+
+      - name: Build
+        # Build your program with the given configuration
+        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --verbose
+
+      - name: Test
+        working-directory: ${{github.workspace}}/build
+        # Execute tests defined by the CMake configuration.
+        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
+        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
+        env:
+          SOCKET_LOG: debug
+
+      - name: Install
+        run: sudo cmake --install build --config Release
+
+      - name: Test Linking
+        working-directory: ${{github.workspace}}/tests/test_find_package
+        run: |
+          eval "$(brew shellenv)"
+          cmake -B build -DCMAKE_BUILD_TYPE=Release
+          cmake --build build --config Release
+          cd build
+          ./helloworld_server &
+          # Give the server time to start
+          sleep 1
+          rsp=$(curl http://127.0.0.1:49999)
+          if [[ "$rsp" == "Hello, world" ]]; then
+            echo "Test passed"
+            exit 0
+          else
+            echo "Test failed"
+            exit 1
+          fi
+
+  build-linux:
     runs-on: ubuntu-latest
 
     strategy:
@@ -22,58 +81,58 @@ jobs:
         shared: ["ON", "OFF"]
 
     steps:
-    - uses: actions/checkout@v3
-      with:
-        submodules: true
+      - uses: actions/checkout@v3
+        with:
+          submodules: true
 
-    - name: Install LLVM and Clang
-      run: |
-        wget https://apt.llvm.org/llvm.sh
-        chmod +x llvm.sh
-        sudo ./llvm.sh 16 all
-        chmod +x update-alternatives-clang.sh
-        sudo ./update-alternatives-clang.sh 16 9999
+      - name: Install LLVM and Clang
+        run: |
+          wget https://apt.llvm.org/llvm.sh
+          chmod +x llvm.sh
+          sudo ./llvm.sh 16 all
+          chmod +x update-alternatives-clang.sh
+          sudo ./update-alternatives-clang.sh 16 9999
 
-    - name: Install Rust toolchain
-      uses: actions-rs/toolchain@v1
-      with:
-        toolchain: nightly
-        default: true
+      - name: Install Rust toolchain
+        uses: actions-rs/toolchain@v1
+        with:
+          toolchain: nightly
+          default: true
 
-    - name: Configure CMake
-      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
-      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
-      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_SHARED_LIBS=${{ matrix.shared }}
+      - name: Configure CMake
+        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
+        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
+        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_SHARED_LIBS=${{ matrix.shared }}
 
-    - name: Build
-      # Build your program with the given configuration
-      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --verbose
+      - name: Build
+        # Build your program with the given configuration
+        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --verbose
 
-    - name: Test
-      working-directory: ${{github.workspace}}/build
-      # Execute tests defined by the CMake configuration.
-      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
-      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
-      env:
-        SOCKET_LOG: debug
+      - name: Test
+        working-directory: ${{github.workspace}}/build
+        # Execute tests defined by the CMake configuration.
+        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
+        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
+        env:
+          SOCKET_LOG: debug
 
-    - name: Install
-      run: sudo cmake --install build --config Release
+      - name: Install
+        run: sudo cmake --install build --config Release
 
-    - name: Test Linking
-      working-directory: ${{github.workspace}}/tests/test_find_package
-      run: |
-        cmake -B build -DCMAKE_BUILD_TYPE=Release
-        cmake --build build --config Release
-        cd build
-        ./helloworld_server &
-        rsp=$(curl http://127.0.0.1:49999)
-        # Give the server time to start
-        sleep 1
-        if [[ "$rsp" == "Hello, world" ]]; then
-          echo "Test passed"
-          exit 0
-        else
-          echo "Test failed"
-          exit 1
-        fi
+      - name: Test Linking
+        working-directory: ${{github.workspace}}/tests/test_find_package
+        run: |
+          cmake -B build -DCMAKE_BUILD_TYPE=Release
+          cmake --build build --config Release
+          cd build
+          ./helloworld_server &
+          # Give the server time to start
+          rsp=$(curl http://127.0.0.1:49999)
+          sleep 1
+          if [[ "$rsp" == "Hello, world" ]]; then
+            echo "Test passed"
+            exit 0
+          else
+            echo "Test failed"
+            exit 1
+          fi
